version: '3.5'
services:
    mysql:
        container_name: mysqlcontainer
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - "./db-spring.sql:/docker-entrypoint-initdb.d/1.sql"
        ports:
          - '3306:3306'
        networks:
          - juke
    backend:
        container_name: backend
        restart: always
        build:
            context: backend
            dockerfile: ./Dockerfile
        image: backend:latest
        ports:
            - 8080:8080
        depends_on: 
            - mysql
        command: ["./wait-for-it.sh", "mysql:3306"]
        networks:
            - juke
    frontend:
        container_name: frontend
        build:
            context: frontend
            dockerfile: ./Dockerfile
        image: frontend:latest
        ports:
            - 8085:80
        networks:
            - juke

networks:
    juke:
        driver: bridge